spring:
  datasource:
    url: jdbc:sqlserver://localhost:1434;databaseName=universidades;encrypt=false;
    username: MAOF
    password: mario0610
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        naming.physical-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
server:
  port: 8181